version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - backend

  course-listing:
    image: ankushatcryptoskool/course-listing-v1
    container_name: course-listing-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/testdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge
